### ISSUE TITLE
Add blackboard value support to LeafCall and LeafTween

### ISSUE THREAD

**Issue by Shadowblitz16** [ThePat02/BehaviourToolkit#68]
Tween isn't very useful due to the fact that a blackboard variable can't be used.

Consider adding the ability to tween to an exiting blackboard value

**Comment by Shadowblitz16** [comment]
https://github.com/ThePat02/BehaviourToolkit/issues/69 could get around this issue by using a setter but this would still be nice

**Comment by ThePat02** [comment]
There is the possibility to add custom value using the CUSTOM_SCRIPT option

**Comment by Shadowblitz16** [comment]
> There is the possibility to add custom value using the CUSTOM_SCRIPT option

The requires a script though can we have the possibility to tween a blackboard value?

**Comment by ThePat02** [comment]
You can just use internal scripts so they don't clutter your project. If you want you can try implementing it yourself tho, but Blackboards can hold any values so it's a mess

**Comment by Shadowblitz16** [comment]
just use a godot 4.0 tween and allow us to supply a blackboard values as a parameter

**Comment by ThePat02** [comment]
This problem goes a bit deeper.

Regarding `LeafCall`:
There are plans to implement custom scripting there, but it wasn't a priority. Just filling in Blackboard values is also not possible, since the `arguments` Array is used for setting arguments in the editor. There is no way to create a custom type in GDScript, so you cannot simply add a new value with the Type "BlackBoardValue" or something to the array. I could not come up with a solution that doesn't seem very hacky, broken or unintuitive.

Regarding `LeafTween`:
When you look at the code, you can see it already uses 4.X tweens. I don't think other tweens are even available. Blackboard values are not implemented yet, because there might be massive changes to how blackboards work in general going forward, as they come with many pitfalls right now. 

But as always: If you absolutely need a certain feature, you can always implement it yourself and even open a pull requests.
